name: Build, Compile, Test & SonarCloud Analysis

on:
  push:
    branches:
      - master
      - develop
      - feature # La pipeline se activa en estas ramas
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

  workflow_dispatch:

jobs:
  build-and-test-and-sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build, Compilar y Ejecutar Pruebas con Maven
        run: mvn -B clean verify

      # Paso para instalar jq (necesario siempre si se van a usar las APIs después)
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # PASO CLAVE: Perform SonarCloud Scan y extraer CE Task ID
      # ESTE PASO SOLO SE EJECUTA SI LA RAMA ES 'master'
      - name: Perform SonarCloud Scan and Extract CE Task ID (Master Branch Only)
        id: sonar_scan_process
        if: github.ref == 'refs/heads/master' # <-- Condición clave: solo si es la rama master
        run: |
          echo "Starting SonarCloud analysis and capturing output..."
          mvn -B sonar:sonar -Dsonar.projectKey=pjserrano:kafka_microservices -Dsonar.organization=pedrojserrano -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SONAR_TOKEN }} > sonar_scan_output.log 2>&1
          
          echo "--- Full Sonar Scan Output (from file) ---"
          cat sonar_scan_output.log
          echo "------------------------------------------"

          CE_TASK_ID=$(grep "More about the report processing at https://sonarcloud.io/api/ce/task?id=" sonar_scan_output.log | grep -o 'id=[^[:space:]]*' | cut -d'=' -f2)
          
          if [ -z "$CE_TASK_ID" ]; then
            echo "Error: Could not find CE Task ID in the SonarCloud scan output log. Check 'sonar_scan_output.log' above for issues."
            exit 1
          fi
          
          echo "Captured CE Task ID: $CE_TASK_ID"
          echo "CE_TASK_ID=$CE_TASK_ID" >> $GITHUB_OUTPUT
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # PASO DE VERIFICACIÓN DEL QUALITY GATE
      # ESTE PASO SOLO SE EJECUTA SI LA RAMA ES 'master'
      - name: Check SonarCloud Quality Gate Status via API (Master Branch Only)
        id: check_quality_gate_api
        if: github.ref == 'refs/heads/master' # <-- Condición clave: solo si es la rama master
        run: |
          CE_TASK_ID="${{ steps.sonar_scan_process.outputs.CE_TASK_ID }}"
          
          if [ -z "$CE_TASK_ID" ]; then
            echo "Error: CE Task ID not found from previous step. Cannot check Quality Gate."
            exit 1
          fi

          echo "Checking Quality Gate for SonarCloud CE Task ID: $CE_TASK_ID"
          
          MAX_RETRIES=20
          WAIT_SECONDS=10
          
          for i in $(seq 1 $MAX_RETRIES); do
            echo "Attempt $i/$MAX_RETRIES: Querying SonarCloud API for task status..."
          
            API_RESPONSE=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
              "https://sonarcloud.io/api/ce/task?id=$CE_TASK_ID")
          
            echo "API Response for CE task: $API_RESPONSE"
          
            TASK_STATUS=$(echo "$API_RESPONSE" | jq -r '.task.status')
          
            if [ "$TASK_STATUS" == "SUCCESS" ]; then
              ANALYSIS_ID=$(echo "$API_RESPONSE" | jq -r '.task.analysisId')
              echo "Analysis ID from CE task: $ANALYSIS_ID"

              if [ "$ANALYSIS_ID" == "null" ] || [ -z "$ANALYSIS_ID" ]; then
                echo "Analysis finished, but analysisId is null/empty. Waiting for it to appear..."
                sleep $WAIT_SECONDS
                continue
              fi

              QUALITY_GATE_RESPONSE=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
                "https://sonarcloud.io/api/qualitygates/project_status?analysisId=$ANALYSIS_ID")
          
              echo "API Response for Quality Gate: $QUALITY_GATE_RESPONSE"
          
              QUALITY_GATE_STATUS=$(echo "$QUALITY_GATE_RESPONSE" | jq -r '.projectStatus.status')

              if [ "$QUALITY_GATE_STATUS" == "null" ] || [ -z "$QUALITY_GATE_STATUS" ]; then
                echo "Quality Gate status not yet available, or API response malformed. Waiting..."
                sleep $WAIT_SECONDS
                continue
              else
                echo "SonarCloud analysis completed. Quality Gate Status: $QUALITY_GATE_STATUS"
                echo "qualityGateStatus=$QUALITY_GATE_STATUS" >> $GITHUB_OUTPUT
                break
              fi

            elif [ "$TASK_STATUS" == "PENDING" ] || [ "$TASK_STATUS" == "IN_PROGRESS" ]; then
              echo "SonarCloud analysis is still $TASK_STATUS. Waiting..."
              sleep $WAIT_SECONDS
            else
              echo "SonarCloud analysis failed on SonarCloud side with status: $TASK_STATUS"
              ERROR_MESSAGE=$(echo "$API_RESPONSE" | jq -r '.errors[0].msg // "No specific error message."')
              echo "SonarCloud Error: $ERROR_MESSAGE"
              echo "qualityGateStatus=ERROR" >> $GITHUB_OUTPUT
              exit 1
            fi
          
            if [ $i -eq $MAX_RETRIES ]; then
              echo "Max retries reached. SonarCloud analysis did not complete successfully or QG status could not be retrieved."
              echo "qualityGateStatus=ERROR" >> $GITHUB_OUTPUT
              exit 1
            fi
          done
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: bash {0}

      # PASO DE FALLO (solo si el Quality Gate se ejecutó y falló)
      - name: Fail on Quality Gate failure
        # Aquí también necesitamos la condición de rama, porque si los pasos anteriores se saltaron,
        # 'steps.check_quality_gate_api.outputs.qualityGateStatus' estará vacío y podría causar un fallo inesperado.
        if: github.ref == 'refs/heads/master' && steps.check_quality_gate_api.outputs.qualityGateStatus != 'OK'
        run: |
          echo "SonarCloud Quality Gate failed! Please check the SonarCloud dashboard for details: https://sonarcloud.io/dashboard?id=pjserrano%3Akafka_microservices"
          exit 1

      - name: Subir Informes de Pruebas
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: surefire-reports
          path: '**/target/surefire-reports'

      - name: Subir artefactos de build
        uses: actions/upload-artifact@v4
        with:
          name: java-artefactos-build
          path: target/*.jar